### ISSUE TITLE
MINOS & ORBSLAM Integration Issue

### ISSUE THREAD

**Issue by zaranasir456** [aliaxam153/RL-ORBSLAM3#2]
We are facing these two issues;
1. When we make changes in the Minos Simulator.py file, then MINOS donot work.
2. Merger node fails to read image.

Please guide in this regard.

**Comment by aliaxam153** [comment]
Response to your query:
1. Yes, I have modified the procedure so it should work if you follow the steps carefully.
2. I have re-uploaded the file; it should be fine now.
